### ISSUE TITLE
Correcciones y recomendaciones

### ISSUE THREAD

**Issue by martincho222** [MatiasAhumada/proyectofinalFrontEnd#47]
Correciones:
1 cuando voy a Menu(productos) y no esta funcionando el backend, la pagina se rompe, lo correcto seria que no se muestre ningun producto, sin salir de la estetica de la app.

2 readme poco descriptivo al momento de iniciar el proyecto localmente, arreglar url del demo.

Recomendaciones

3 estructura de carpeta, la carpeta components, no debe tener todas las carpetas del proyecto, como por ejemplo Views/pages, ya que la carpeta view trata de una seccion en particular compuesta por varios componentes.
pueden aprender sobre Atomic Design
https://bradfrost.com/blog/post/atomic-web-design/

https://www.uifrommars.com/atomic-design-ventajas/
para entender mejor el concepto de componentes

4 armados de urls para los request, recomendacion utilizar las comillas invertidas o backticks (`${urlUsuario}/${id}`), queda mas lejible que escribirlas de esta forma (urlUsuario + "/" + id)

5 - esta bueno que hayan aprendido a utilizar fetch, pero axios es la herramienta mas utilizada en el mercado laboral ya que te permite realizar configuraciones mas potentes y complejas, creando una instancia sin tener que estar configurando headers en cada uno de los requests al menos que sea necesario.
por ejemplo, ustedes tienen este request

const respuesta = await fetch(urlUsuario, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(usuario),
    });

con axios quedaria de la siguiente manera
const respuesta = await instanciaAxios.post(urlUsuario, usuario)

**Comment by MatiasAhumada** [comment]
hola! buenas tardes! una vez corregidos los puntos 1 y 2 les aviso por
aqui para que revisen ? si esta todo en orden recien nos darian la
cerificacion ?

**Comment by martincho222** [comment]
Buenas tardes Matias, si, una vez tengan corregidos esos puntos, nos avisas por aqui o por slack, lo revisamos nuevamente y si esta correcto, se procede con la certificacion.

**Comment by MatiasAhumada** [comment]
Hola! Buen día. Ya realizamos las correcciones solicitadas! Espero una
respuesta de su parte. Muchas gracias

**Comment by emiarias** [comment]
Cambios aprobados.
